name: mc-MobSpawner
version: '${project.version}'
main: hu.kxtsoo.mobspawner.MobSpawner
author: 'kxtsoo, Zsomi5'
api-version: '1.20'
folia-supported: true

softdepend: [PlaceholderAPI]

libraries:
  - dev.dejvokep:boosted-yaml:1.3
  - com.zaxxer:HikariCP:5.1.0
  - com.h2database:h2:2.1.214